#!/bin/bash

# Check for Homebrew, Install if we don't have it
if test ! $(which brew); then
    echo '================================================================================'
    echo 'Installing homebrew...'
  echo "Installing homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    echo 'Done installing homebrew.'
    echo '================================================================================'
fi

# Update homebrew recipes
echo '================================================================================'
echo 'Installing, updating, and cleaning up brew dependencies...'
brew bundle --global
brew bundle cleanup --force --global
brew services cleanup
sudo brew services cleanup
brew cleanup -s

# make directory in case they aren't already there
mkdir -p "/usr/local/lib"
mkdir -p "/usr/local/bin"

# Install and use latest bash
echo '================================================================================'
echo 'Installing bash'
brew install bash
chsh -s /usr/local/bin/bash

# Install git
brew install git

# Install nvm
echo "Installing nvm..."
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
nvm install stable
nvm alias default stable

# Centralize global npm packages for different node versions
echo "prefix = /usr/local" > ~/.npmrc

# Install Brew Cask
echo "Installing brew cask..."
brew install caskroom/cask/brew-cask

brew tap 'homebrew/cask'
brew tap 'homebrew/cask-drivers'
brew tap 'homebrew/cask-versions'
brew tap 'homebrew/services'

# php monitor
brew tap 'nicoverbruggen/homebrew-cask'

# dependencies
brew install 'pkg-config'

# Install foudations
echo '================================================================================'
echo "installing foundations..."
brew install 'composer'
brew install 'dnsmasq'
brew install 'redis'
brew install 'rabbitmq'
brew install 'watchman'
brew install 'mysql'
brew install 'php@8.1'
brew install 'php@8.0'
brew install 'php@7.4'
brew install 'yarn'
brew install 'node'
brew install 'pnpm'
brew install 'sqlite'
brew install 'nginx'
brew install 'mongodb-community'
brew install 'grep'
brew install 'vim'
brew install 'zsh'
brew install 'zsh-async'
brew install 'zsh-autosuggestions'
brew install 'zsh-syntax-highlighting'
brew install 'sonarqube'
brew install 'gnupg'
brew install 'coreutils'
brew install 'beanstalkd'
echo '================================================================================'
echo "Done installing foundations..."

echo '================================================================================'
echo 'Installing and updating composer dependencies...'
composer global update
valet install
echo 'Done installing and updating composer dependencies.'
echo '================================================================================'

echo '================================================================================'
echo 'Installing and updating pecl dependencies...'
pecl update-channels
# For whatever reason, brew is symlinking to the following directory, but it doesn't exist
# and extensions can't be installed. This should resolve that.
mkdir /usr/local/lib/php/pecl -p

# pecl upgrade will also install if it isn't yet installed, where as pecl
# install will fail if it is installed.
pecl upgrade pcov
echo 'Done installing and updating pecl dependencies.'
echo '================================================================================'

# install terminal theme
echo '================================================================================'
echo 'Installing and updating terminal theme...'
curl --create-dirs -fLo $HOME/.config/kitty/dracula.conf https://raw.githubusercontent.com/dracula/kitty/master/dracula.conf
echo 'Done installing and updating terminal theme.'
echo '================================================================================'

# Apps
# apps=(
#   # google-chrome
#   firefox
#   iterm2
#   docker
#   postman
#   tableplus
#   fig
#   zoom
#   phpstorm
#   goland
#   raycast
#   DBngin
#   phpmon
#   linear
#   skype
#   imageoptim
# )

# Install apps to /Applications
# Default is: /Users/$user/Applications
echo "installing apps..."
# brew install --cask --appdir="/Applications" ${apps[@]}
brew install --cask iterm2 --appdir="/Applications"
brew install --cask docker --appdir="/Applications"
brew install --cask postman --appdir="/Applications"
brew install --cask tableplus --appdir="/Applications"
brew install --cask zoom --appdir="/Applications"
brew install --cask phpmon --appdir="/Applications"
brew install --cask skype --appdir="/Applications"
brew install --cask imageoptim --appdir="/Applications"
brew install --cask DBngin --appdir="/Applications"
brew install --cask linear --appdir="/Applications"
brew install --cask fig --appdir="/Applications"
brew install --cask raycast --appdir="/Applications"

# clone this repo
git clone https://github.com/dammy001/dotfiles ~/.dotfiles

# Make some commonly used folders
mkdir ~/Personal
mkdir ~/Work
mkdir ~/Damilare

# Source dot files
echo '. ~/.dotfiles/bash/.profile' >> ~/.profile
source ~/.profile

echo 'Done!'